# Generated by Django 4.1.3 on 2022-11-15 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VotersRoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('surname', models.CharField(max_length=300)),
                ('constituency', models.CharField(choices=[('Harare', 'Harare'), ('MashWest', 'MashWest'), ('MashEast', 'MashEast'), ('MashCentral', 'MashCentral'), ('Manicaland', 'Manicaland')], max_length=300)),
                ('is_registered', models.BooleanField(default=True)),
                ('id_number', models.CharField(max_length=300)),
            ],
        ),
    ]
